version: '3.9'
services:

  postgresql:
    image: postgres:15
    container_name: postgresql
    hostname: scrapper
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: postgres_data:/var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  liquibase-migrations:
      image: liquibase/liquibase:4.18
      depends_on:
        - postgresql
      command:
        - --hub-mode=off
        - --changelog-file=master.xml
        - --driver=org.postgresql.Driver
        - --url=jdbc:postgresql://postgresql:5432/scrapper
        - --username=postgres
        - --password=postgres
        - update
      volumes:
        - ./migrations:/liquibase/changelog
      networks:
        - backend

networks:
  backend:

volumes:
  postgres_data:

  migrations: