version: '3.9'
services:

  postgres:
    image: postgres:15
    container_name: scrapper-postgres
    hostname: scrapper
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=scrapper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  liquibase-migrations:
      image: liquibase/liquibase:4.18
      depends_on:
        - postgres
      command:
        - --hub-mode=off
        - --changelog-file=master.xml
        - --driver=org.postgresql.Driver
        - --url=jdbc:postgresql://postgresql:5432/scrapper
        - --username=postgres
        - --password=postgres
        - update
      volumes:
        - ./migrations:/liquibase/changelog
      networks:
        - backend

networks:
  backend:
    name: backend
    external: false

volumes:
  postgres_data:
    external: false
    name: postgres_data
  migrations:
    external: false
    name: migrations_data